# Generated by Django 5.2 on 2025-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('gambar', models.ImageField(upload_to='gambar_berita/')),
                ('link', models.URLField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
